openapi: 3.0.1
info:
  title: Stack Analyses API
  version: "2.0"
servers:
  - url: https://f8a-analytics-2445582058137.{environment}.gw.apicast.io/api/v2
    variables:
      environment:
        default: production # Production server
        enum:
          - production # Production server
          - staging # Staging server

security: # All endpoints needs 3scale user_key, refer securitySchemes
  - tokenAuth: []

paths:
  /stack-analyses:
    post:
      tags:
      - Scan Services
      summary: Initiates a scan to gather security and other details about an application
        stack and related recommendations to improve the stack
      parameters:
      - name: ecosystem
        in: header
        description: The ecosystem of the stack analysis being called.
        required: true
        schema:
          type: string
      - name: origin
        in: header
        description: This is required to give an indication as to from where is the
          request getting generated. If from VScode extension, the value which we
          need to send is 'vscode'.
        schema:
          type: string
          default: vscode
          enum:
            - vscode
      - name: show_transitive
        in: header
        description: This is required to enable or disable the transitive support.
          We need to pass the value as 'true' if transitive is needed. Default value
          is 'false'.
        schema:
          type: boolean
          default: true
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
              - filePath[]
              - manifest[]
              properties:
                manifest[]:
                  type: string
                  description: A manifest file dependencies.txt for maven, npmlist.json
                    for npm & pylist.json for pypi. Commands to generate these files
                    are mentioned in the README.md
                  format: binary
                filePath[]:
                  type: string
                  description: The absolute or relative path where the manifest file
                    is located. This has to be mandatorily provided with the manifest[]
                    parameter and vice versa.
        required: true
      responses:
        200:
          description: Response with the unique identifier for the stack analysis
            request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserStackIdentifier'
        400:
          description: Bad request
          content: {}
        401:
          description: Request Unauthorized
          content: {}
  /stack-analyses/{request-id}:
    get:
      tags:
      - Scan Services
      summary: Get security and other details about an application stack and related
        recommendations to improve the stack
      parameters:
      - name: request-id
        in: path
        description: stack analysis request id
        required: true
        schema:
          type: string
      responses:
        200:
          description: Detailed response for the requested application component
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StackAnalysesReport'
        401:
          description: Request unauthorized
          content: {}
        404:
          description: Data not found
          content: {}
        408:
          description: Request has timed out on server
          content: {}
components:
  schemas:
    VulnerabilityDetailsForRegisteredUser:
      title: VulnerabilityForRegisteredUser
      allOf:
        - $ref: '#/components/schemas/PremiumVulnerabilityFields'
        - oneOf:
          - $ref: '#/components/schemas/PublicVulnerabilityDetails'
          - $ref: '#/components/schemas/PrivateVulnerabilityDetails'
      description: Vulnerability details for registered users
    VulnerabilityDetailsForFreeTier:
      title: VulnerabilityDetailsForFreeTier
      oneOf:
        - $ref: '#/components/schemas/PublicVulnerabilityDetails'
        - $ref: '#/components/schemas/BasicPrivateVulnerabilityDetails'
      description: Vulnerability details for unregistered users
    BasicVulnerabilityFields:
      title: VulnerabilityBase
      properties:
        cvss:
          type: number
          format: float
          example: 9.8
        cvss_v3:
          type: string
          example: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
        severity:
          type: string
          enum:
          - low
          - medium
          - high
          - critical
        title:
          type: string
          example: SQL Injection
        id:
          type: string
        url:
          type: string        
      description: Limited private vulnerability details for free tier users
    PremiumVulnerabilityFields:
      title: ExtendedVulnerabilityFields
      type: object
      properties:
        malicious:
          type: boolean
          default: false
        patch_exists:
          type: boolean
        fixable:
          type: boolean
        exploit:
          type: string
        description:
          type: string
        fixed_in:
          type: string
        references:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
              url:
                type: string
      description: Extended Vulnerability details, available only to registered users
    PublicVulnerabilityDetails:
      title: PublicVulnerabilityDetails
      description: Publicaly known Vulnerability details with associated CVES
      allOf:
        - $ref: '#/components/schemas/BasicVulnerabilityFields'
        - type: object
          properties:
            cve_ids:
              type: array
              items:
                type: string
    PrivateVulnerabilityDetails:
      title: PrivateVulnerabilityDetails
      allOf:
        - $ref: '#/components/schemas/BasicVulnerabilityFields'
      description: Private vulnerability details
    BasicPrivateVulnerabilityDetails:
      title: BasicPrivateVulnerabilityDetails
      allOf:
        - $ref: '#/components/schemas/BasicVulnerabilityFields'
      description: Basic private vulnerability details
    Package:
      title: Package
      type: object
      properties:
        name:
          type: string
          example: django
        version:
          type: string
          example: 1.2.1
      description: Package details
    PackageWithTransitives:
      title: PackageWithTransitives
      allOf:
        - $ref: '#/components/schemas/Package'
        - type: object
          properties:
            deps:
              type: array
              items:
                $ref: '#/components/schemas/Package'
      description: Package details with transitives
    UnknownLicenses:
      title: UnknownLicenses
      type: object
      properties:
        component_conflict:
          type: array
          items:
            type: object
            properties: {}
        really_unknown:
          type: array
          items:
            type: object
            properties: {}
      description: Data of licenses unknown to the system
    LicenseAnalysis:
      title: LicenseAnalysis
      type: object
      properties:
        outlier_packages:
          type: array
          items:
            type: object
            properties: {}
        derived_stack_licenses:
          type: array
          items:
            type: string
        conflict_packages:
          type: array
          items:
            type: string
        current_stack_license:
          type: object
          properties: {}
        unknown_licenses:
          $ref: '#/components/schemas/UnknownLicenses'
      description: License analyses data
    GitHubDetails:
      title: GitHubDetails
      type: object
      properties:
        watchers:
          type: integer
        first_release_date:
          type: string
        total_releases:
          type: integer
        issues:
          type: object
          properties: {}
        pull_requests:
          type: object
          properties: {}
        dependent_repos:
          type: integer
        open_issues_count:
          type: integer
        latest_release_duration:
          type: string
        forks_count:
          type: integer
        contributors:
          type: integer
        size:
          type: string
        stargazers_count:
          type: integer
        used_by:
          type: array
          items:
            type: string
        dependent_projects:
          type: integer
      description: Github details
    PackageDetailsBase:
      title: PackageDetailsBase
      allOf:
        - $ref: '#/components/schemas/Package'
        - type: object
          properties:
            latest_version:
              type: string
              example: 3.0.5
            github:
              $ref: '#/components/schemas/GitHubDetails'
            licenses:
              type: array
              items:
                type: string
            topic_list:
              type: array
              items:
                type: string
            ecosystem:
              type: string
            public_vulnerabilities_count:
              type: integer
            private_vulnerabilities_count:
              type: integer
            affected_direct_deps:
              type: array
              description: Lists all direct dependencies of this package
              items:
                type: object
                properties:
                  package:
                    type: string
                  version:
                    type: string
            osio_user_count:
              type: integer
          description: Details of the package
    RecommendedVersionForPublicVulnerabilities:
      title: RecommendedVersionForPublicVulnerabilities
      properties:
        recommended_version:
            type: string
            example: 3.0.0
      description: Recommended package version which includes only fix public vulnerability
    RecommendedVersionForPublicAndPrivateVulnerabilities:
      title: RecommendedVersionForPublicAndPrivateVulnerabilities
      properties:
        recommended_version:
            type: string
            example: 3.0.0
      description: Recommended package version which includes fix for public and private vulnerability
    PackageDetailsForRegisteredUser:
      title: PackageDetailsForRegisteredUser
      allOf:
        - $ref: '#/components/schemas/PackageDetailsBase'
        - $ref: '#/components/schemas/RecommendedVersionForPublicAndPrivateVulnerabilities'
        - type: object
          properties:
            public_vulnerabilities:
              type: array
              description: Publicly known vulnerability details
              items:
                $ref: '#/components/schemas/VulnerabilityDetailsForRegisteredUser'
            private_vulnerabilities:
              type: array
              description: Private vulnerability details, available only to registered
                users
              items:
                $ref: '#/components/schemas/VulnerabilityDetailsForRegisteredUser'
          description: Details of the package for registered users
    PackageDetailsForFreeTier:
      title: PackageDetailsForFreeTier
      allOf:
        - $ref: '#/components/schemas/PackageDetailsBase'
        - $ref: '#/components/schemas/RecommendedVersionForPublicVulnerabilities'
        - type: object
          properties:
            public_vulnerabilities:
              type: array
              description: Publicly known vulnerability details
              items:
                $ref: '#/components/schemas/VulnerabilityDetailsForFreeTier'
            private_vulnerabilities:
              type: array
              description: Private vulnerability details with limited info
              items:
                $ref: '#/components/schemas/VulnerabilityDetailsForFreeTier'
          description: Details of the package for free tier users      
    RecommendedPackageData:
      title: RecommendedPackageData
      description: Recommended packages data
      allOf:
      - oneOf:
        - $ref: '#/components/schemas/PackageDetailsForFreeTier'
        - $ref: '#/components/schemas/PackageDetailsForRegisteredUser'
      - type: object
        properties:
          confidence_reason:
            type: number
            format: float
          reason:
            type: string
          topic_list:
            type: array
            items:
              type: string
    StackRecommendation:
      title: StackRecommendation
      type: object
      properties:
        companion:
          type: array
          items:
            $ref: '#/components/schemas/RecommendedPackageData'
        manifest_file_path:
          type: string
        usage_outliers:
          type: array
          items:
            type: object
            properties: {}
        alternate:
          type: array
          items:
            $ref: '#/components/schemas/RecommendedPackageData'
      description: Application stack recommendations
    StackAnalysesResult:
      title: StackAnalysesResult
      type: object
      properties:
        manifest_file_path:
          type: string
        manifest_name:
          type: string
        unknown_dependencies:
          type: array
          items:
            $ref: '#/components/schemas/Package'
        ecosystem:
          type: string
        unknown_dependencies_count:
          type: integer
        analyzed_dependencies:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/PackageDetailsForFreeTier'
              - $ref: '#/components/schemas/PackageDetailsForRegisteredUser'
        analyzed_dependencies_count:
          type: integer
        license_analysis:
          $ref: '#/components/schemas/LicenseAnalysis'
        distinct_licenses:
          type: array
          items:
            type: string
        stack_license_conflict:
          type: boolean
        dependencies:
          type: array
          items:
            $ref: '#/components/schemas/PackageWithTransitives'
        total_licenses:
          type: integer
        recommendation_ready:
          type: boolean  
        recommendation:
          $ref: '#/components/schemas/StackRecommendation'
      description: Stack analyses result data
    StackAnalysesReport:
      title: StackAnalysesReport
      type: object
      properties:
        result:
          type: array
          items:
            $ref: '#/components/schemas/StackAnalysesResult'
      description: Response structure for stack analyses
    UserStackIdentifier:
      title: UserStackIdentifier
      type: object
      properties:
        id:
          type: string
        status:
          type: string
        submitted_at:
          type: string
      description: Response structure for stack analyses post call
  securitySchemes:
    tokenAuth:
      type: apiKey
      description: 3Scale user key
      name: user_key
      in: query